site_name: 'Bash-my-AWS'
site_description:
    Bash-my-AWS is a simple but powerful set of CLI commands for managing
    resources on Amazon Web Services. They harness the power of Amazon's AWSCLI,
    while abstracting away verbosity.
site_author: 'Mike Bailey'
site_url: 'https://bash-my-aws.org/'
google_analytics: ['UA-154550647-1', 'bash-my-aws.org']

nav:
  - Home: index.md
  # - Tour: tour.md
  - Command Reference: command-reference.md
  - Pipe-Skimming: pipe-skimming.md
  - CloudFormation Naming: cloudformation-naming.md
  - LCA 2020 Video: linuxconf2020.md

theme:
  name: material
repo_name: 'bash-my-aws/bash-my-aws'
repo_url: 'https://github.com/bash-my-aws/bash-my-aws'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bash-my-aws'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta



